spring:
  application:
    name: file-service
  config:
    import: "configserver:"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    gcp:
      storage:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: refresh


