spring:
  application:
    name: file-service
  config:
    import: "configserver:"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: refresh


