server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bhavanichandra/exl_hackathon
          search-paths: secrets
          username: bhavanichandra
          password: "Add-your-cipher-password-here"
          default-label: main

encrypt:
  keystore:
    location: classpath:configserver.jks
    password: md3v3l0p3r  # JKS Password, store it in some safe place or deploy the application in secure place
    alias: config