server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bhavanichandra/exl_hackathon
          search-paths: secrets
          username: bhavanichandra
          password: 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