log4j:
  appender:
    stdout:
      Target: System.out
      layout:
        nodeValue: org.apache.log4j.PatternLayout
        ConversionPattern: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
      nodeValue: org.apache.log4j.ConsoleAppender
  rootLogger: INFO,console
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [ %-20.20thread ] %5p -> %-25.25logger{25} ->
      %m%n'
  level:
    org:
      springframework:
        web:
          client: INFO
