server:
  port: ${PORT:8081}

spring:
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

environment:
  active: "dev"

download:
  link:
    active:
      time: 10
azure:
  api:
    base:
      url: "https://azure1poc2.blob.core.windows.net"
  token:
    url: "https://login.microsoftonline.com"

jwt:
  secret: "{cipher}AQAQEBlevER2gURhrfE0EctvW194ekigDVItrJH/qLVlaIGDhhzfhK+/z2vkFQyOUox/kUgzTC38r2eW4APXUOhQo6H3TVg9gv4Z3NB6YdHjIRtu3goQXIL3UC9kFBzipG/yoIuoutaKMkIqZgbEAAUUkO8+/fOuDsW5UFZw8A3MjywjsbdBLI3/hImLq6vJ2Jz9Ni6m/BAqQoe62OEVvkvrWBVx2yQ5P0ipthQzsbr7QdLmEZNqBXCJLneWBvy0USfIq6l06by5+OndDC1uUNxjjMbTrRvtUkkSDpHrvl6fPoqQJA6L3AJ3fKw9H1JsknDPq3FOiD2GjeCFB/UwiiLEt/k2eC1U4utWfGuKz79y3QLO5/mh2Zt549o0Mw2sh4w="
