server:
  port: ${PORT:8081}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "{cipher}AQBAqUpIp87C1N3P8jHncCtu/b1IO0y8xX0SiA1WB0wEvT91R2N2OktHsrSzPbb7cDVbRcZREm6+xtImo8LbcScfEQPpJVIyDGHaaUot+yW/QprIxXbwKh9nb+h8b46bSldYusgfNWQWdAfOD5K+LXKqh3R4hMI3owjhh2nYb5wJq7iao3WItkqg5D+YIrnLX/S9jC8JwiKHb7K0Ve44Bt2e/ahP3FxegcoZ4NRIuZE15/rEegJa4diQolKTxjaHHqCIZb2TPnEQIldDIvzblHBk6uH1BnHOf5B/JefSxiL7y8k+abGbjQgJc/VEaJxXAQDY8fo5LgCav6nIyPfNfdIbFP3AogPm5YH5E4SdWEB/RA0eBhHKxRGLPt90kjHuNiQ="
    url: jdbc:postgresql://192.168.0.133:5432/postgres
    password: "{cipher}AQBAqUpIp87C1N3P8jHncCtu/b1IO0y8xX0SiA1WB0wEvT91R2N2OktHsrSzPbb7cDVbRcZREm6+xtImo8LbcScfEQPpJVIyDGHaaUot+yW/QprIxXbwKh9nb+h8b46bSldYusgfNWQWdAfOD5K+LXKqh3R4hMI3owjhh2nYb5wJq7iao3WItkqg5D+YIrnLX/S9jC8JwiKHb7K0Ve44Bt2e/ahP3FxegcoZ4NRIuZE15/rEegJa4diQolKTxjaHHqCIZb2TPnEQIldDIvzblHBk6uH1BnHOf5B/JefSxiL7y8k+abGbjQgJc/VEaJxXAQDY8fo5LgCav6nIyPfNfdIbFP3AogPm5YH5E4SdWEB/RA0eBhHKxRGLPt90kjHuNiQ="
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

environment:
  active: "dev"

download:
  link:
    active:
      time: 10
azure:
  api:
    base:
      url: "https://azure1poc2.blob.core.windows.net"
  token:
    url: "https://login.microsoftonline.com"

jwt:
  secret: "{cipher}AQAQEBlevER2gURhrfE0EctvW194ekigDVItrJH/qLVlaIGDhhzfhK+/z2vkFQyOUox/kUgzTC38r2eW4APXUOhQo6H3TVg9gv4Z3NB6YdHjIRtu3goQXIL3UC9kFBzipG/yoIuoutaKMkIqZgbEAAUUkO8+/fOuDsW5UFZw8A3MjywjsbdBLI3/hImLq6vJ2Jz9Ni6m/BAqQoe62OEVvkvrWBVx2yQ5P0ipthQzsbr7QdLmEZNqBXCJLneWBvy0USfIq6l06by5+OndDC1uUNxjjMbTrRvtUkkSDpHrvl6fPoqQJA6L3AJ3fKw9H1JsknDPq3FOiD2GjeCFB/UwiiLEt/k2eC1U4utWfGuKz79y3QLO5/mh2Zt549o0Mw2sh4w="
