temp:
  location: "/Users/bhavanichandra/personal/hackathon/temp_dir"

encryption:
  key: "{cipher}AQAU1/NMMNcDkRRSuUdRhYrFwOU6xKV3BNMFnxDpjMgRtgXpIRfDWabb++CkCSwkR9H7FU3g77DsPYzioC+j0ujK/IMHDtfl5FSTFCXnpumhZcMyMCtQQN801s04+tke1NVeguCsN2D5i19g37S7hNbQzYU+e7VOqypwNUGaE/lqS9uMw7+DPrMGRa+hlclG94ItXc1IPr6RS2ymbC3foeMEE+TkARpw5x8ZoOOHZK/S0MLGgNTvMayGPimmblkidaKkgDBFtGpl3iwA90/g+ditmRtBJaUgrcSYubpTFGRr/jmS5QW5a77f48VL7Pe3pk5uaLwyEdT9eKjn9TUmGkc39hYqTDiXWGRFp/F8k5zVSHOkdXBSRy99hRwLZ2Mw01qbAn3dAIBb4QTPv7FiMBcS"
  iv: "{cipher}AQBr6mjEbZXOtuVhI8Ex/fSCKkhNyaIUN1iJSzbjOHTLOaNnG7tRV1T8ZG1hSR/LYihYJeySI2cM23/TdhKadsPLsJoEimOMhXdVcsHiNe+HKC6C3pmPOks4rleYlz3DhOFQXpETv0DAl6dTmJH6FzdVknIl5y5eyGxxyhpBv4AqYeuhgC/fNj8p3FbiWa+xK6Ls8NpTMryUrWdLa1nC3wFxCuZcwl37MmWIDToNce6qMbG8F6gx4Opd4COHi38MFRpuzvKMQDx/0yRWoqnbUgCMkZALjDsfcq+jov4NRQN0cKdff/Jyrl55ZxBLT6mIfuwELkV+PMSq8He5VTPREG293aQYSTZPLs2DsFGrido/y0daUdxs5vlzSB9fLh3DCVPSQ9DaXDGffGMGE+CVFJtM"

server:
  port: ${PORT:8081}

spring:
  data:
    mongodb:
      uri: "{cipher}AQAHD6wwb0fxhkf4whrAfyxXs8IjQqdmDXiLFOBmMryOBI7oIa4VFMS0anHk4ojJG6PdatzIytwKNNyFtVLB+LHiK90G7we2IRU052ZOz7osXU8KuVrDxdLfjuFnrS+1S1mbY05hR1muKmsqJH9BDhSw4eXZIG9s7/lP+W5fdYGVaOMzAsuTv0kA/WrqPvzR5ytU0IULf9R+7thi0nvFQrcZ9s+peoUYCa5Ws8fv80KDObHv2YGxRD+uyZrrXaGocg2RBHWjeb6ciCJgRkqSenxzjgO5A4vT0hwGz+gSAKwcOuiJyQWRzVU88O0/6gQzk5fLFDYthd2DJ3j/AtZ2PJK/WHBu8LI0oE+nnfbyQKNRazUEG2Gc8S840q3zt5YB/w79kn2NGQgW/49j8pV4cVOdCJwnN1g13b8JsM/Bqd7oabqSK+2XZDFekoUDfjLPHn6yJiigB/MuESg7t2oNmITaa1pVpP47+GIu+VyDOyz17EKqiEIvKV8APJ1IWdEx7co="
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

environment:
  active: "dev"

download:
  link:
    active:
      time: 10

jwt:
  secret: "{cipher}AQAQEBlevER2gURhrfE0EctvW194ekigDVItrJH/qLVlaIGDhhzfhK+/z2vkFQyOUox/kUgzTC38r2eW4APXUOhQo6H3TVg9gv4Z3NB6YdHjIRtu3goQXIL3UC9kFBzipG/yoIuoutaKMkIqZgbEAAUUkO8+/fOuDsW5UFZw8A3MjywjsbdBLI3/hImLq6vJ2Jz9Ni6m/BAqQoe62OEVvkvrWBVx2yQ5P0ipthQzsbr7QdLmEZNqBXCJLneWBvy0USfIq6l06by5+OndDC1uUNxjjMbTrRvtUkkSDpHrvl6fPoqQJA6L3AJ3fKw9H1JsknDPq3FOiD2GjeCFB/UwiiLEt/k2eC1U4utWfGuKz79y3QLO5/mh2Zt549o0Mw2sh4w="
