spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: '{cipher}AQA3whmsImwDfzyfF0qdoYpR/SYG8HZfGQUt7ikcb/ANSBqQo0Zmw7J1wQUkpqhxnQkVqnyU0SaeXS48con1IF7GiU8QKSDPpEP0wZvfufhd5kdy3VtjtJEVQaMbn3u4p4DtUBafBrWWA3W7TQp61fFz7BcqtUDxBvJ1DkRYjkS1HIVKcWnR1ZlcmJJSr8zfcIREJ/NSFn8BQVjwZeFzogEkCDNCAgm0cgdeUkBeIUusIXOy/7FjMYkQSikY79g4hqSmhz1D83aNxsTfvpo40Ttx7PEDpDiZIT1mVeGqPVbMjtqR2X5qEb9H43gPlYbAgfQOLzHPlFp8xWgv1GghRdoTqY8ERLoiD7f5xP/7/THtoK49efcuVTqsPZJJmy7InSc=%'
    url: jdbc:postgresql://192.168.0.133:5432/postgres
    password: '{cipher}AQA3whmsImwDfzyfF0qdoYpR/SYG8HZfGQUt7ikcb/ANSBqQo0Zmw7J1wQUkpqhxnQkVqnyU0SaeXS48con1IF7GiU8QKSDPpEP0wZvfufhd5kdy3VtjtJEVQaMbn3u4p4DtUBafBrWWA3W7TQp61fFz7BcqtUDxBvJ1DkRYjkS1HIVKcWnR1ZlcmJJSr8zfcIREJ/NSFn8BQVjwZeFzogEkCDNCAgm0cgdeUkBeIUusIXOy/7FjMYkQSikY79g4hqSmhz1D83aNxsTfvpo40Ttx7PEDpDiZIT1mVeGqPVbMjtqR2X5qEb9H43gPlYbAgfQOLzHPlFp8xWgv1GghRdoTqY8ERLoiD7f5xP/7/THtoK49efcuVTqsPZJJmy7InSc=%'
server:
  port: ${PORT:8081}
