server:
  port: ${PORT:8081}

spring:
  data:
    mongodb:
      username: "development"
      password: "{cipher}AQBPUTpoNxoYs+btP+Jz1xHH8Tf5EhYJYEZurVkaW9ehHMvh8/C2VewMQ61eGpXYxB//4FsvPLTcw+hU1VPyQNwzpBE1qhk6V/rLBo4wl6cwQdj/Raxh6OGPdqGr9j28CZNeJ6Xx+31RVF21FRPkQlATe6iU17l1s3FDF8G4SYMKXaZmxj0MTtwNdYIMct44wGWz7aISyfvKJ9E8aJA5Tp/RwkshvFWvrNThUiYZiJ/UTkVL314XDqDhOEQeWV3cAWIcpVLJbgg5gBeMFSTpPvLLzrg9wgHRlKmyFU8+5xE+cNinUOQVjYA/sZzgIGl7jgoZFew+ziMkiHrZY3nL3ldGatD3hOeBOeEyX8BGsbu9AdhEAgT9noPx7dC2J9r5fnTVRpmvSLK3ElN59g6PmhiE"
      database: exl_hackathon
      host: cluster0.yerkz.mongodb.net
      replica-set-name: atlas-uq1g8b-shard-0
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

environment:
  active: "dev"

download:
  link:
    active:
      time: 10
azure:
  api:
    base:
      url: "https://azure1poc2.blob.core.windows.net"
  token:
    url: "https://login.microsoftonline.com"

jwt:
  secret: "{cipher}AQAQEBlevER2gURhrfE0EctvW194ekigDVItrJH/qLVlaIGDhhzfhK+/z2vkFQyOUox/kUgzTC38r2eW4APXUOhQo6H3TVg9gv4Z3NB6YdHjIRtu3goQXIL3UC9kFBzipG/yoIuoutaKMkIqZgbEAAUUkO8+/fOuDsW5UFZw8A3MjywjsbdBLI3/hImLq6vJ2Jz9Ni6m/BAqQoe62OEVvkvrWBVx2yQ5P0ipthQzsbr7QdLmEZNqBXCJLneWBvy0USfIq6l06by5+OndDC1uUNxjjMbTrRvtUkkSDpHrvl6fPoqQJA6L3AJ3fKw9H1JsknDPq3FOiD2GjeCFB/UwiiLEt/k2eC1U4utWfGuKz79y3QLO5/mh2Zt549o0Mw2sh4w="
