spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "{cipher}AQBAqUpIp87C1N3P8jHncCtu/b1IO0y8xX0SiA1WB0wEvT91R2N2OktHsrSzPbb7cDVbRcZREm6+xtImo8LbcScfEQPpJVIyDGHaaUot+yW/QprIxXbwKh9nb+h8b46bSldYusgfNWQWdAfOD5K+LXKqh3R4hMI3owjhh2nYb5wJq7iao3WItkqg5D+YIrnLX/S9jC8JwiKHb7K0Ve44Bt2e/ahP3FxegcoZ4NRIuZE15/rEegJa4diQolKTxjaHHqCIZb2TPnEQIldDIvzblHBk6uH1BnHOf5B/JefSxiL7y8k+abGbjQgJc/VEaJxXAQDY8fo5LgCav6nIyPfNfdIbFP3AogPm5YH5E4SdWEB/RA0eBhHKxRGLPt90kjHuNiQ="
    url: jdbc:postgresql://192.168.0.133:5432/postgres
    password: "{cipher}AQBAqUpIp87C1N3P8jHncCtu/b1IO0y8xX0SiA1WB0wEvT91R2N2OktHsrSzPbb7cDVbRcZREm6+xtImo8LbcScfEQPpJVIyDGHaaUot+yW/QprIxXbwKh9nb+h8b46bSldYusgfNWQWdAfOD5K+LXKqh3R4hMI3owjhh2nYb5wJq7iao3WItkqg5D+YIrnLX/S9jC8JwiKHb7K0Ve44Bt2e/ahP3FxegcoZ4NRIuZE15/rEegJa4diQolKTxjaHHqCIZb2TPnEQIldDIvzblHBk6uH1BnHOf5B/JefSxiL7y8k+abGbjQgJc/VEaJxXAQDY8fo5LgCav6nIyPfNfdIbFP3AogPm5YH5E4SdWEB/RA0eBhHKxRGLPt90kjHuNiQ="
server:
  port: ${PORT:8081}
